workspace(name = "rules_lua_examples")

load("@com_github_michaelboulton_rules_lua//lua:repositories.bzl", "luajit_register_toolchains")

luajit_register_toolchains()

load("@com_github_michaelboulton_rules_lua//fennel:repositories.bzl", "fennel_register_toolchains")

fennel_register_toolchains(
    name = "fennel",
    version = "1.2.1",
)

load("@com_github_michaelboulton_rules_lua//fennel:deps.bzl", "aniseed_dependencies")

aniseed_dependencies()

load("@com_github_michaelboulton_rules_lua//lua:defs.bzl", "github_dependency", "luarocks_dependency")

luarocks_dependency(
    dependency = "luafilesystem",
    sha256 = "576270a55752894254c2cba0d49d73595d37ec4ea8a75e557fdae7aff80e19cf",
    user = "hisham",
    version = "1.8.0-1",
)

luarocks_dependency(
    dependency = "stdlib",
    sha256 = "67eadaccbb2b6037ea70129f9616da49eaeeaf1477652a8e2cc77740286531cf",
    user = "gvvaughan",
    version = "41.2.2-1",
)

github_dependency(
    dependency = "luasec",
    tag = "v1.2.0",
    user = "brunoos",
    version = "1.2.0-1",
)

github_dependency(
    name = "lua_inspect",
    dependency = "inspect.lua",
    rockspec_path = "rockspecs/inspect-3.1.2-0.rockspec",
    tag = "v3.1.3",
    user = "kikito",
    version = "3.1.3-0",
)

load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

new_git_repository(
    name = "lua_luassert",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_files",
    srcs = glob(["**/*"], exclude=["**/* *"]),
)

load("@com_github_michaelboulton_rules_lua//lua:defs.bzl", "luarocks_library")

luarocks_library(
    name = "lua_luassert",
    srcrock = "luassert-scm-1.rockspec",
    data = [":all_files"],
)
    """,
    commit = "f14abce580feec35a0279c92118ae7e4c3382789",
    remote = "https://github.com/lunarmodules/luassert.git",
)
